/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoDictationRouteImport } from './routes/demo-dictation'
import { Route as IndexRouteImport } from './routes/index'

const DemoDictationRoute = DemoDictationRouteImport.update({
  id: '/demo-dictation',
  path: '/demo-dictation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-dictation': typeof DemoDictationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-dictation': typeof DemoDictationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-dictation': typeof DemoDictationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo-dictation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo-dictation'
  id: '__root__' | '/' | '/demo-dictation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoDictationRoute: typeof DemoDictationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-dictation': {
      id: '/demo-dictation'
      path: '/demo-dictation'
      fullPath: '/demo-dictation'
      preLoaderRoute: typeof DemoDictationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoDictationRoute: DemoDictationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
